included:
  - FlipperDevicesInc-MultiTransportConnectivityLayer-TestTask
  
analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_import
  - unused_declaration
  
opt_in_rules:
  - all
  
disabled_rules:
  - no_empty_block
  - contrasted_opening_brace
  - one_declaration_per_file
  - trailing_whitespace
  - xctfail_message
  - private_unit_test
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - lower_acl_than_parent
  - missing_docs
  - return_value_from_void_function
  - strong_iboutlet
  - conditional_returns_on_newline
  - explicit_type_interface
  - no_extension_access_modifier
  - no_grouping_extension
  - identifier_name
  - weak_delegate
  - type_name
  - switch_case_on_newline
  - statement_position
  - function_default_parameter_at_end
  - void_function_in_ternary
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - object_literal
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - raw_value_for_camel_cased_codable_enum
  - required_deinit
  - fallthrough
  - self_binding
  - unavailable_function
  - indentation_width
  - reduce_into
  - sorted_enum_cases
  - superfluous_else
  - empty_xctest_method
  - balanced_xctest_lifecycle
  - class_delegate_protocol
  - todo
  - notification_center_detachment
  - unused_control_flow_label
  - prefer_nimble
  - xct_specific_matcher
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - test_case_accessibility
  - fatal_error_message
  - implicit_return
  - untyped_error_in_catch
  - generic_type_name

attributes:
  always_on_same_line:
    - "@objc"
    - "@Environment"
  always_on_line_above:
    - "@RuleConfigurationDescriptionBuilder"
    - "@ConfigurationElement"
    - "@OptionGroup"
    
force_try:
  severity: warning

force_cast:
  severity: warning

number_separator:
  minimum_length: 5
